version: 0.0
os: linux
hooks:
  ApplicationStop:
    - location: stop.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: start.sh
      timeout: 300
      runas: ec2-user

