version: 0.0
os: linux
files:
  - source: scripts/
    destination: /home/ec2-user/scripts
hooks:
  ApplicationStop:
    - location: stop.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: start.sh
      timeout: 300
      runas: ec2-user

