version: 0.0
os: linux

files:
  - source: stop.sh
    destination: stop.sh
  - source: start.sh
    destination: start.sh

hooks:
  ApplicationStop:
    - location: stop.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: start.sh
      timeout: 300
      runas: ec2-user

